apiVersion: v1
kind: ResourceQuota
metadata:
  name: msvc-quota
  namespace: msvc-ns
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 8Gi

---

apiVersion: v1
kind: LimitRange
metadata:
  name: msvc-default-resources
  namespace: msvc-ns
spec:
  limits:
    - default:
        cpu: "300m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "256Mi"
      type: Container
