apiVersion: v1
kind: ResourceQuota
metadata:
  name: msvc-quota
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 4Gi

---

apiVersion: v1
kind: LimitRange
metadata:
  name: msvc-default-resources
spec:
  limits:
    - default:
        memory: "512Mi"
        cpu: "250m"
      defaultRequest:
        memory: "256Mi"
        cpu: "50m"
      type: Container
